name: hami_guide
description: "دليل الحامي للخدمات والأنشطة المحلية."
publish_to: 'none'
version: 1.0.2+3

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # المكتبات المستخدمة
  url_launcher: ^6.2.1
  flutter_map: ^8.3.1
  latlong2: ^0.10.1
  geolocator: ^14.0.3
  image_picker: ^1.0.4
  # مثبت على 4.8.0 لتوافق xml 6.x مع flutter_local_notifications 19.5.0
  image: 4.8.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.16.0
  sqflite: ^2.4.3
  sqflite_common: ^2.5.11
  path: ^1.9.1
  shared_preferences: ^2.5.3
  workmanager: ^0.9.0+3
  flutter_local_notifications: ^19.5.0
  firebase_core: ^4.12.1
  firebase_messaging: ^16.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  sqflite_common_ffi: ^2.4.2

# 1. إعدادات أيقونة التطبيق (تكون في مستوى منفصل)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21

# 2. إعدادات فلاتر (الخطوط، الصور، وأيقونات النظام)
flutter:
  # هذا السطر هو المسؤول عن ظهور أيقونات التطبيق (Icons.home وغيرها)
  uses-material-design: true

  # تعريف مجلد الصور
  assets:
    - assets/

  # تعريف الخطوط
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
