import '../../models/service_category.dart';

abstract final class AppCatalog {
  static const List<String> advertisements = [
    'مساحة إعلانية مميزة 1',
    'تخفيضات كبرى في قسم البناء',
    'سجل الآن في الدليل مجاناً',
  ];

  static const List<ServiceCategory> services = [
    ServiceCategory(
      id: 'local-emergency',
      name: 'طوارئ',
      slug: 'emergency',
      iconName: 'emergency',
      sortOrder: 10,
      displayGroup: CategoryDisplayGroup.services,
    ),
    ServiceCategory(
      id: 'local-pharmacies',
      name: 'صيدليات',
      slug: 'pharmacies',
      iconName: 'local_pharmacy',
      sortOrder: 20,
      displayGroup: CategoryDisplayGroup.services,
    ),
    ServiceCategory(
      id: 'local-clinics',
      name: 'عيادات',
      slug: 'clinics',
      iconName: 'medical_services',
      sortOrder: 30,
      displayGroup: CategoryDisplayGroup.services,
    ),
    ServiceCategory(
      id: 'local-restaurants',
      name: 'مطاعم',
      slug: 'restaurants',
      iconName: 'restaurant',
      sortOrder: 40,
      displayGroup: CategoryDisplayGroup.services,
    ),
    ServiceCategory(
      id: 'local-kitchens',
      name: 'مطابخ',
      slug: 'kitchens',
      iconName: 'soup_kitchen',
      sortOrder: 50,
      displayGroup: CategoryDisplayGroup.services,
    ),
    ServiceCategory(
      id: 'local-buffets',
      name: 'بوفيات',
      slug: 'buffets',
      iconName: 'fastfood',
      sortOrder: 60,
      displayGroup: CategoryDisplayGroup.services,
    ),
    ServiceCategory(
      id: 'local-wholesale-shops',
      name: 'محلات جملة / تجزئة',
      slug: 'wholesale-shops',
      iconName: 'inventory_2',
      sortOrder: 70,
      displayGroup: CategoryDisplayGroup.services,
    ),
    ServiceCategory(
      id: 'local-fishing-marine-tools',
      name: 'صيد/أدوات بحر',
      slug: 'fishing-marine-tools',
      iconName: 'phishing',
      sortOrder: 80,
      displayGroup: CategoryDisplayGroup.services,
    ),
    ServiceCategory(
      id: 'local-electronics',
      name: 'إلكترونيات',
      slug: 'electronics',
      iconName: 'devices',
      sortOrder: 90,
      displayGroup: CategoryDisplayGroup.services,
    ),
    ServiceCategory(
      id: 'local-building-materials',
      name: 'مواد بناء',
      slug: 'building-materials',
      iconName: 'home_repair_service',
      sortOrder: 100,
      displayGroup: CategoryDisplayGroup.services,
    ),
    ServiceCategory(
      id: 'local-groceries',
      name: 'بقالات',
      slug: 'groceries',
      iconName: 'storefront',
      sortOrder: 110,
      displayGroup: CategoryDisplayGroup.services,
    ),
    ServiceCategory(
      id: 'local-fuel-stations',
      name: 'محطات',
      slug: 'fuel-stations',
      iconName: 'local_gas_station',
      sortOrder: 120,
      displayGroup: CategoryDisplayGroup.services,
    ),
    ServiceCategory(
      id: 'local-other-services',
      name: 'أعمال منزلية',
      slug: 'other-services',
      iconName: 'home_repair_service',
      sortOrder: 130,
      displayGroup: CategoryDisplayGroup.services,
    ),
    ServiceCategory(
      id: 'local-salons',
      name: 'صوالين',
      slug: 'salons',
      iconName: 'content_cut',
      sortOrder: 140,
      displayGroup: CategoryDisplayGroup.services,
    ),
    ServiceCategory(
      id: 'local-workshops',
      name: 'ورش متنوعة',
      slug: 'workshops',
      iconName: 'build',
      sortOrder: 150,
      displayGroup: CategoryDisplayGroup.services,
    ),
    ServiceCategory(
      id: 'local-laundries',
      name: 'مغاسل متنوعة',
      slug: 'laundries',
      iconName: 'local_laundry_service',
      sortOrder: 160,
      displayGroup: CategoryDisplayGroup.services,
    ),
    ServiceCategory(
      id: 'local-freelance-work',
      name: 'أعمال حره',
      slug: 'freelancework',
      iconName: 'work_outline',
      sortOrder: 240,
      displayGroup: CategoryDisplayGroup.services,
    ),
    ServiceCategory(
      id: 'local-studios',
      name: 'استيديوهات',
      slug: 'studios',
      iconName: 'photo_camera',
      sortOrder: 250,
      displayGroup: CategoryDisplayGroup.services,
    ),
    ServiceCategory(
      id: 'local-simple-and-grilled',
      name: 'بساط ومشاوي',
      slug: 'simpleandgrilled',
      iconName: 'outdoor_grill',
      sortOrder: 260,
      displayGroup: CategoryDisplayGroup.services,
    ),
    ServiceCategory(
      id: 'local-associations',
      name: 'جمعيات',
      slug: 'associations',
      iconName: 'volunteer_activism',
      sortOrder: 270,
      displayGroup: CategoryDisplayGroup.services,
    ),
    ServiceCategory(
      id: 'local-fruits-vegetables',
      name: 'خضروات وفواكة',
      slug: 'fruitsvegetables',
      iconName: 'eco',
      sortOrder: 280,
      displayGroup: CategoryDisplayGroup.services,
    ),
    ServiceCategory(
      id: 'local-internet-networks',
      name: 'شبكات انترنت',
      slug: 'internetnetworks',
      iconName: 'router',
      sortOrder: 290,
      displayGroup: CategoryDisplayGroup.services,
    ),
    ServiceCategory(
      id: 'local-private-work',
      name: 'عمل خاص',
      slug: 'privatework',
      iconName: 'business_center',
      sortOrder: 300,
      displayGroup: CategoryDisplayGroup.services,
    ),
    ServiceCategory(
      id: 'local-bakeries',
      name: 'مخابز',
      slug: 'bakeries',
      iconName: 'bakery_dining',
      sortOrder: 310,
      displayGroup: CategoryDisplayGroup.services,
    ),
    ServiceCategory(
      id: 'local-government-facilities',
      name: 'مرافق حكومية',
      slug: 'governmentfacilities',
      iconName: 'account_balance',
      sortOrder: 320,
      displayGroup: CategoryDisplayGroup.services,
    ),
    ServiceCategory(
      id: 'local-art-and-gift-offices',
      name: 'مكاتب تحف وهدايا',
      slug: 'artandgiftoffices',
      iconName: 'card_giftcard',
      sortOrder: 330,
      displayGroup: CategoryDisplayGroup.services,
    ),
  ];

  static const List<ServiceCategory> transport = [
    ServiceCategory(
      id: 'local-work-equipment',
      name: 'معدات عمل',
      slug: 'work-equipment',
      iconName: 'engineering',
      sortOrder: 170,
      displayGroup: CategoryDisplayGroup.transport,
    ),
    ServiceCategory(
      id: 'local-water-tankers',
      name: 'بوز ماء',
      slug: 'water-tankers',
      iconName: 'water_drop',
      sortOrder: 180,
      displayGroup: CategoryDisplayGroup.transport,
    ),
    ServiceCategory(
      id: 'local-transport-trucks',
      name: 'سيارات نقل',
      slug: 'transport-trucks',
      iconName: 'local_shipping',
      sortOrder: 190,
      displayGroup: CategoryDisplayGroup.transport,
    ),
    ServiceCategory(
      id: 'local-tuk-tuks',
      name: 'تكاتك',
      slug: 'tuk-tuks',
      iconName: 'electric_rickshaw',
      sortOrder: 200,
      displayGroup: CategoryDisplayGroup.transport,
    ),
    ServiceCategory(
      id: 'local-noha-vehicles',
      name: 'سيارات نوها',
      slug: 'noha-vehicles',
      iconName: 'airport_shuttle',
      sortOrder: 210,
      displayGroup: CategoryDisplayGroup.transport,
    ),
    ServiceCategory(
      id: 'local-taxis',
      name: 'تكاسي',
      slug: 'taxis',
      iconName: 'local_taxi',
      sortOrder: 220,
      displayGroup: CategoryDisplayGroup.transport,
    ),
    ServiceCategory(
      id: 'local-delivery-motorcycles',
      name: 'دراجات توصيل',
      slug: 'delivery-motorcycles',
      iconName: 'motorcycle',
      sortOrder: 230,
      displayGroup: CategoryDisplayGroup.transport,
    ),
    ServiceCategory(
      id: 'local-travel-agencies',
      name: 'مكاتب وسفريات',
      slug: 'travelagencies',
      iconName: 'flight_takeoff',
      sortOrder: 340,
      displayGroup: CategoryDisplayGroup.transport,
    ),
  ];

  static List<ServiceCategory> get allCategories => [
        ...services,
        ...transport,
      ];
}
